services:
  frontend:
    build:
      context: ./
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: services-network      